### ISSUE TITLE
can we get a patch release to unlock the use of newtonsoft 13

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Newtonsoft.Json#133]

**Comment by danielmarbach** [comment]
@SimonCropp will take care of it in the next days

**Comment by SimonCropp** [comment]
thanks @danielmarbach

**Comment by danielmarbach** [comment]
A new minor https://github.com/Particular/NServiceBus.Newtonsoft.Json/releases/tag/2.3.0 is out. It will take a while until SqlPersistence is updated like you asked in the other repo

**Comment by SimonCropp** [comment]
awesome
