### ISSUE TITLE
 JsonMessageSerializer insecure by default (TypeNameHandling.Auto)

### ISSUE THREAD

**Issue by aledefault** [Particular/NServiceBus.Newtonsoft.Json#184]
Since [TypeNameHandling](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_TypeNameHandling.htm) other than **None** is insecure when deserialize from external source, doesn't make this NewtonsoftSerializer insecure by default?

What is the reason because **TypeNameHandling.Auto** have been choose by default? Should this be reflected in the [documentation](https://docs.particular.net/nservicebus/serialization/newtonsoft)?

**Comment by andreasohlund** [comment]
You are correct, we are just about to start the work to switch the default to `None` in a way that doesn't break existing users. We'll keep you in the loop on this issue as we progress so stay tuned.

**Comment by jpalac** [comment]
The change is published in [NServicebus.Newtonsoft.Json release 2.4](https://github.com/Particular/NServiceBus.Newtonsoft.Json/releases/tag/2.4.0)
