### ISSUE TITLE
Incompatible with latest version of NSB 

### ISSUE THREAD

**Issue by jonnybonbon** [Particular/NServiceBus.Newtonsoft.Json#2]
I believe the latest version of NSB has a different interface for implementing a custom serialiser. 

Using this serialiser with the latest version now returns the error:

"Method 'ProvidedByFeature' on type 'NServiceBus.Newtonsoft.Json.NewtonsoftSerializer' from assembly 'NServiceBus.Newtonsoft.Json, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' is overriding a method that is not visible from that assembly"

**Comment by SimonCropp** [comment]
Jonny

I am having trouble reproducing your problem.

If u run http://docs.particular.net/samples/serializers/json-external/ , which uses the newest nugets, i dont get your error.

Could you share a repro?

**Comment by jonnybonbon** [comment]
Sorry. Think I must have been using the old newtonsoft adapter. All working with the latest versions.

**Comment by SimonCropp** [comment]
@jonnybonbon glad to hear you are moving forward again.
