### ISSUE TITLE
An enveloped message fails deserialization

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus.Newtonsoft.Json#34]
I have a test case which fails - basically I have a message within a message.

Deserialization fails because json.net is trying to load type `IBaseMessage_impl` - the message mapper generated type.  My reason for putting a message inside a message is weird I know but there is a good reason I can go into if you want.  

I've fixed this in my own code by supplying `JsonSerializerSettings` with a SerializationBinder which converts types during serialization from `IBaseMessage_impl` back to `IBaseMessage`

I know a while ago you guys were using the `ContractResolver` and `SerializationBinder` settings for serialization - not sure what changed but the fix is basically to do that again.  I've essentially copied the `IMessageSerializer` interface for my own project [here](https://github.com/volak/Aggregates.NET/tree/netstandard/src/Aggregates.NET.NewtonsoftJson/Internal) and now have NSB use my serialization which handles enveloped messages.   

```

[TestFixture]
public class With_enveloped_message
{
    [Test]
    public void Deserialize()
    {
        var messageMapper = new MessageMapper();
        var serializer = new JsonMessageSerializer(messageMapper, null, null, null, null);
        var messageTypes = new[]
        {
            typeof(IBaseMessage), typeof(IEnvelope)
        };
        messageMapper.Initialize(messageTypes);
        var message = messageMapper.CreateInstance<IBaseMessage>(x => x.SomeProperty = "test");
        var envelope = messageMapper.CreateInstance<IEnvelope>(x => x.Message = message);
        using (var stream = new MemoryStream())
        {
            serializer.Serialize(envelope, stream);

            stream.Position = 0;
            var result = (IEnvelope)serializer.Deserialize(stream, messageTypes)[0];

            Assert.AreEqual("test", (result.Message as IBaseMessage).SomeProperty);
        }

    }

    public interface IEnvelope : IMessage
    {
        object Message { get; set; }
    }

    public interface IBaseMessage : IMessage
    {
        string SomeProperty { get; set; }
    }
}
```

**Comment by timbussmann** [comment]
yeah I think we don't map message property types which causes this issue as the proxy classes should only really be used as the root message type. Is there any reason you can't use a concrete class instead of `IBaseMessage`?

**Comment by volak** [comment]
Yeah I do use a concrete type envelope - this same test also fails

```

    [Test]
    public void Deserialize()
    {
        var messageMapper = new MessageMapper();
        var serializer = new JsonMessageSerializer(messageMapper, null, null, null, null);
        var messageTypes = new[]
        {
            typeof(IBaseMessage), typeof(Envelope)
        };
        messageMapper.Initialize(messageTypes);
        var message = messageMapper.CreateInstance<IBaseMessage>(x => x.SomeProperty = "test");
        var envelope = new Envelope {Message = message};
        using (var stream = new MemoryStream())
        {
            serializer.Serialize(envelope, stream);

            stream.Position = 0;
            var result = (Envelope)serializer.Deserialize(stream, messageTypes)[0];

            Assert.AreEqual("test", (result.Message as IBaseMessage).SomeProperty);
        }

    }

    public class Envelope : IMessage
    {
        public object Message { get; set; }
    }

    public interface IBaseMessage : IMessage
    {
        string SomeProperty { get; set; }
    }
```

**Comment by volak** [comment]
This is the serialization binder that will convert property types inside messages back to their interface type

```

    class EventSerializationBinder : DefaultSerializationBinder
    {
        private readonly IEventMapper _mapper;

        public EventSerializationBinder(IEventMapper mapper)
        {
            _mapper = mapper;
        }

        public override void BindToName(Type serializedType, out string assemblyName, out string typeName)
        {
            var mappedType = serializedType;
            if (!serializedType.IsInterface)
                mappedType = _mapper.GetMappedTypeFor(serializedType) ?? serializedType;

            assemblyName = null;
            typeName = mappedType.AssemblyQualifiedName;
        }
    }
```

Like I mention before I know the binder was used around NSB 4.0 or 5.0 days - not sure why things changed but this is the only way I know how to fix this

**Comment by bording** [comment]
@volak I believe @timbussmann was asking why you're using `public interface IBaseMessage : IMessage`

instead of defining it as a class: `public class BaseMessage : IMessage`.

**Comment by volak** [comment]
Ah I see - as an interface is the point of the test.  
The envelope will serialize as something like

```
{
    "message": {
        "$type": "IBaseMessage_impl, NServiceBusProxies",
        "someProperty": "test"
    }
}
```

That `$type` field breaks the deserializer because Json.net can't `Type.Load("IBaseMessage_impl, NServiceBusProxies")`

The envelope's message type is just `object` so it could be anything - a concrete command or an interface event.  If you put an event in there it breaks - is all I'm saying.

**Comment by timbussmann** [comment]
the envelope's type can be either an interface or a message as it's the root type ("the message type") and that should be correctly converted forth and back between proxy and interface type when serializing deserializing. For message properties, we do not map every message property type towards a potential proxy class, that's why I'm asking why you can't use `public class BaseMessage : IMessage` as the type for your wrapped messages, as this should allow correct deserialization.

**Comment by volak** [comment]
Right - I understand the intent to only handle the top most type, but I'm enveloping events so to fix this with this serializer I'd have to convert all my events from interfaces to types.  

I do like events being interfaces since that prevents other programmers from doing something silly `new MyEvent()` but that also presents problems when going in and out of NSB.  

I save all my events into geteventstore - and have to convert between `IEvent_impl` and `IEvent` all the time to eliminate all instances of `_impl` types from things the other endpoints see.

IMHO since NSB is creating this proxy it would strive to make the proxy as invisible as possible (my related discuss thread https://discuss.particular.net/t/sending-message-objects-ends-up-with-ugly-event-impl-enclosed-type/287/7)
which would include writing the correct `$type` information for JSON .NET.  

But perhaps enveloping events can just be something that is "if you do it provide your own serializer" kind of thing.  Its certainly not hard to fix this by sending a new `JsonSerializerSettings` or writing a simple serializer like I did.

**Comment by timbussmann** [comment]
at the current point I think that writing your custom serialization config or even serializer seems to be the way around this if you indeed want to stick with the current approach. This is far beyond a regular usage of the NSB core apis and I'm not really sure whether there is much value in complicating the serializer to be able to deal with scenarios we don't really recommend (using proxy types as nested property types). Thoughts?

**Comment by volak** [comment]
Its fine with me - like I said I've already fixed the issue for me its just a really easy fix so I brought it up 👍

**Comment by timbussmann** [comment]
@volak it's always highly appreciated and welcomed if you bring up something like that. It's definitely something we're looking at closely to see whether this is a scenario we think we should support out of the box (or at least a better configuration option) or not. So thanks again for raising this issue 👍
