### ISSUE TITLE
Update to json newtonsoft  11.0.1

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Newtonsoft.Json#36]

**Comment by andreasohlund** [comment]
Do you need this for the v6 or v7 compatible version?

**Comment by SimonCropp** [comment]
Depends on the timeline for nsb v7. Basically you will be blocking people from updating until there is a new release. My feeling is if nsb v7 is more than a week away u need to release anew nsb v6 version

**Comment by andreasohlund** [comment]
Will take a look, there seems to be some breaking changes http://apicomparer.particular.net/compare/newtonsoft.json/10.0.3...11.0.1 so we'll see how we can do the versioning of the nsb adapter

**Comment by andreasohlund** [comment]
Assuming that there will be breaking changes needed we will need to figure out how to version the nuget package. Perhaps `NServiceBus.Newtonsoft.Json.v6` ? (since `v2.0` is already reserved for v7)

**Comment by SimonCropp** [comment]
please no version numbers in the nuget name. makes upgrades a pain. 

given for other packages you have previously only bumped minor 

 * https://www.nuget.org/packages/NServiceBus.Autofac/5.1.0 depends on autofac 4
 * https://www.nuget.org/packages/NServiceBus.Autofac/5.0.0 depends on autofac 3.5

i think the same can be done here

**Comment by SimonCropp** [comment]
can u release a new RC asap. as this is already giving me nuget version conflict grief

**Comment by SimonCropp** [comment]
https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/38

https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/37

**Comment by andreasohlund** [comment]
Thanks @SimonCropp I will make sure we act on this

As an aside, what are your thoughts on the case where we would have to make a breaking change on our part. Would you propose to:

1. Break semver and still release a minor
2. Release a new nuget with the version in the name (I don't like this either)
3. Some other idea?

**Comment by andreasohlund** [comment]
> as this is already giving me nuget version conflict grief

For completeness, what exact is causing issues? (I assume its the v7 compatible version you need urgently right?)

**Comment by andreasohlund** [comment]
We discussed this internally and will go ahead with the 1.1 release.

We do not want to release a RC since it might break existing RC users and we promise "drop into bin folder in production" compatibility for the RC. 

The ideas that came to mind to get you unstuck is

1. See if we can just up the nuget range but still compile against v10. 
2. Get you a 2.1.0-Beta1 that is compiled against

Thoughts? other ideas?

**Comment by SimonCropp** [comment]
> For completeness, what exact is causing issues

Other nugets we use have already updated to newtonsoft 11. but we cant update to those until the nsb bits unblock us.

> See if we can just up the nuget range but still compile against v10.

This has been discussed many time. and on all those occasions it was decided the particular only targets the single major range, since if u target multiple majors you need to run all tests against each major, and u  are more likely cause people binding redirect pain or diamond dependency pain

> Get you a 2.1.0-Beta1 that is compiled against

happy with that as long as on every change to 2.0 rc you also port and release 2.1 beta. and u release a stable 2.1 at the same time u release a stable 2.0

**Comment by andreasohlund** [comment]
>Other nugets we use have already updated to newtonsoft 11. but we cant update to those until the nsb bits unblock us.

Can you elaborate on how you are blocked, is it nuget that complains are do you need to [assembly redirect](http://blog.rytmis.net/2016/03/29/asp-net-core-and-assembly-binding-redirects/)?

**Comment by andreasohlund** [comment]
Yea I can confirm that it blow up with:

```
Update-Package : Detected package version outside of dependency constraint: NServiceBus.Newtonsoft.Json 2.0.0-rc0001 requires Newtonsoft.Json (>= 10.0.3 && < 11.0.0) but version Newtonsoft.Json 11.0.1 was resolved.
At line:1 char:1
+ Update-Package -IgnoreDependencies
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```
Isn't there a way to force NuGet to install anyway?

**Comment by andreasohlund** [comment]
Tried to manually edit the csprojs but that blows on build

```
Error	NU1107	Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 NServiceBusSample -> NServiceBus.Newtonsoft.Encryption -> Newtonsoft.Json (>= 11.0.1) 
 NServiceBusSample -> NServiceBus.Newtonsoft.Json 1.1.0 -> Newtonsoft.Json (>= 10.0.1 && < 11.0.0).	NServiceBusSample	C:\dev\Newtonsoft.Json.Encryption\NServiceBusSample\NServiceBusSample.csproj	1	
```

**Comment by bording** [comment]
@SimonCropp I've released 1.2.0, and 2.1.0-beta0001 is on MyGet. Can you use a package from our MyGet feed, or do we need to go ahead and push it to nuget.org now?

**Comment by SimonCropp** [comment]
Thanks. Although it would need to be on nuget to consume from work. Also my intermediate side project that target it will also need it on nuget

**Comment by bording** [comment]
In that case I've gone ahead and pushed it to nuget.org as well.

**Comment by SimonCropp** [comment]
Cool

**Comment by andreasohlund** [comment]
Can we close this one?

**Comment by SimonCropp** [comment]
yep. thanks

**Comment by SimonCropp** [comment]
can this be assigned to a milestone

**Comment by andreasohlund** [comment]
Assigned to `2.1.0`
