### ISSUE TITLE
Add IDataBusSerializer implementation

### ISSUE THREAD

**Issue by DixonDs** [Particular/NServiceBus.Newtonsoft.Json#44]
While it is fairly simple to implement and even demonstrated in samples (https://docs.particular.net/samples/databus/custom-serializer/), it would be great if there was an out-of-the-box implementation

**Comment by ramonsmits** [comment]
@DixonDs We have, see https://docs.particular.net/nservicebus/messaging/databus/#enabling-the-databus

We have implementations for:

- FileShare
- Azure Blob Storage
- MongoDB

**Comment by DixonDs** [comment]
@ramonsmits Sorry, I am confused a bit by your comment. Is there a JSON serialization implementation for Data Bus out-of-the-box that could be enabled for one of the options you mentioned? The page that you linked mentions "By default NServiceBus uses a BinaryFormatter to serialize and deserialize DataBus properties." and says that we need a custom `IDataBusSerializer` implementation if we want to use some other serialization format

**Comment by ramonsmits** [comment]
@DixonDs I think I interpreted you incorrectly. You requesting if the provided sample could be included in core to provide an OOTB JSON databus property serializer for the databus?

The only file you would need to add to your solution would be this single 48 line file.

- https://github.com/Particular/docs.particular.net/blob/master/samples/databus/custom-serializer/Core_7/Shared/JsonDataBusSerializer.cs

**Comment by DixonDs** [comment]
@ramonsmits I think it is not really about the number of lines to code/add by ourselves, but rather about having a trusted, officially maintained implementation. There could be further improvements to that implementation, and we would prefer to update the package version than maintain the source code for something that doesn't really belong to our project.

**Comment by dvdstelt** [comment]
Hi @DixonDs, is this still an issue? Could you explain what benefit you'd see when using a different serializer? The binary one works out of the box and is fully supported. If it's about the code from the sample, we'll always be able to offer help, should issues or questions arise.

**Comment by mikeminutillo** [comment]
@DixonDs if this is still an issue, please re-open it.
