### ISSUE TITLE
Update Newtonsoft.Json to 12.0.1 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Newtonsoft.Json#46]

**Comment by WilliamBZA** [comment]
Thanks @SimonCropp, we're tracking this and will make sure it gets done!

**Comment by buvinghausen** [comment]
Can you just remove the upper version constraint? JSON.net is the most ubiquitous library on NuGet and very rarely if ever has breaking changes even with major version bumps.  I'd rather take the pain of reporting an issue with JSON.net 13 than have to wait on you to publish this update.

**Comment by indualagarsamy** [comment]
@SimonCropp - See: https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/47#issuecomment-444385827

**Comment by adamralph** [comment]
@buvinghausen [we're on it](https://github.com/Particular/NServiceBus.Newtonsoft.Json/pull/47#issuecomment-444385827). 🙂

**Comment by SimonCropp** [comment]
Thanks hadi
