### ISSUE TITLE
Custom ContractResolver gets overwritten

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Newtonsoft.Json#5]
In order to have more fine-grained control of the serialization process I would like to provide a custom contract resolver to the serializer. Normally this is passed in using a JsonSerializerSettings instance like this:

```CSharp
config.UseSerialization<NewtonsoftSerializer>()
    .Settings(new JsonSerializerSettings
     {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    });
```

When creating the serializer, [this code](https://github.com/Particular/NServiceBus.Newtonsoft.Json/blob/master/NServiceBus.Newtonsoft.Json/JsonMessageSerializer.cs#L77) overwrites the ContractResolver passed in.

**Comment by andreasohlund** [comment]
Not a blocker for v6, label removed cc @tmasternak @mikeminutillo
