### ISSUE TITLE
Relax Newtonsoft.Json dependency Upper Bound limitation

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus.Newtonsoft.Json#7]
`NServiceBus.Newtonsoft.Json.nuspec` explicitly sets the Newtonsoft.Json upper bound to 8.0.0 [here](https://github.com/Particular/NServiceBus.Newtonsoft.Json/blob/develop/src/NuGetBuild/NServiceBus.Newtonsoft.Json.nuspec#L18):

`<dependency id="Newtonsoft.Json" version="[7.0.0, 8.0.0)" />`

Latest version of Newtonsoft.Json is **[9.0.1](https://www.nuget.org/packages/Newtonsoft.Json/)**.

_Is there a reason for setting the upper bound or can it be safely removed?_

Context:  I'm combining NServiceBus with the .NET Core configuration framework (_not_ running on .net core, but regular dot net framework) which unfortunately has a ridiculously high json requirement, requiring 9.0.1: https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/

**Comment by SimonCropp** [comment]
> Is there a reason for setting the upper bound or can it be safely removed?

you can bypass that and everything should work fine.

What version of NSB are you using.

**Comment by ppittle** [comment]
@SimonCropp: Using NSB 6 beta4 and NSB.Json Beta 1

I've tested and `NServiceBus.NewtonSoft.Json` works fine when `Netwonsoft.Json` 9.0.1 is referenced in my project.  

However, because of the upper bound restriction in the nuspec, NuGet complains and I have to force installs.  It also breaks NuGet restores in some scenarios (at least pretty sure this is the culprit).

So if this works fine using Netwonsoft.Json above 7, there should't be any reason for the upper bound restriction.

From [NuGet documentation](http://docs.nuget.org/Create/Versioning#guidance)

> Generally, the guidance in most cases is to only specify a lower bound, and leave the upper bound open.

**Comment by SimonCropp** [comment]
I pushed a new nuget. Can u try that

**Comment by ppittle** [comment]
Trying now.

**Comment by hbulens** [comment]
Support for the latest Newtonsoft.Json package would be great for new ASP.NET Core projects which use 9.0.1 by default. So if there's no reason for the upper bound, could you publish a new NuGet version?

**Comment by SimonCropp** [comment]
@ppittle sorry i missed your comment

I pushed beta 4 to nuget. can u try now 

@hbulens are you also using the NSB v6 beta?

**Comment by ppittle** [comment]
@SimonCropp - Confirmed.  1.0.0-beta0004 meets my needs of supporting 9.  

I'd still argue that pegging the lower bound dependency is probably unnecessary,  unless you're using something new in Json and would maximize comparability support with:

    <dependency id="Newtonsoft.Json" version="7.0.0" />

**But,** this my initial concern is fixed, so I'm good to go.  Thanks @SimonCropp !!

**Comment by SimonCropp** [comment]
@ppittle the problem with lower bound ranges like that is the support and testing implications. ie all test have to run against a greater range of versions. unless there is a compelling reason i would like to avoid that extra effort

**Comment by ppittle** [comment]
Fair enough, minimizing testing effort is a pretty valid argument in my book!

**Comment by hbulens** [comment]
@SimonCropp I didn't use 6.x until last week. I feared the upgrade from 5 to 6 would be difficult but as it turns out, it was actually fairly easy.

**Comment by SimonCropp** [comment]
@hbulens good to hear. out of curiosity did u use the upgrade guide? http://docs.particular.net/nservicebus/upgrades/5to6  and if so how useful was it?

**Comment by hbulens** [comment]
@SimonCropp I did use the upgrade guide, I thought it was complete and easy to follow. I'm not using any advanced capabilities (yet) so there was little to modify. Still, what I had to do was there in the docs so no complaints there!
